web/views/schedule.py
from datetime import datetime

import pytz
from icalendar import Calendar, Event

from flask import Blueprint, render_template, jsonify, Response, url_for, abort

from web.utils import get_data_file, get_markdown_file

schedule = Blueprint('schedule', __name__)

tz = pytz.timezone('Canada/Eastern')


@schedule.route('/')
def index():
    """
    Schedule index page.
    """
    schedule = get_data_file('schedule.json')

    return render_template('pages/schedule/index.html', schedule=schedule)


@schedule.route('/<string:slug>/')
def talk(slug):
    """
    Talk details page.
    """
    content, meta = get_markdown_file('talks/{}'.format(slug), 'en')

    return render_template('pages/schedule/talk.html', content=content,
                           meta=meta, slug=slug)


@schedule.route('/<string:slug>.json')
def talk_json(slug):

    if slug == 'schedule':
        content = get_data_file('schedule.json')
    else:
        description, content = get_markdown_file('talks/{}'.format(slug), 'en')

        # The Markdown Meta extension gives us everything in lists.
        # So this is a simple converter.
        for k, v in content.items():
            content[k] = v[0]

        content['description'] = description

    return jsonify(content)


def event_ics(slug):
    description, content = get_markdown_file('talks/{}'.format(slug), 'en')

    if not content:
        abort(404)

    for k, v in content.items():
        content[k] = v[0]

    start_time = datetime.strptime('{0} {1}'.format(content['date'],
                                                    content['start_time']),
                                   '%Y-%m-%d %H:%M:%S')

    end_time = datetime.strptime('{0} {1}'.format(content['date'],
                                                  content['end_time']),
                                 '%Y-%m-%d %H:%M:%S')

    event = Event()

    if content.get('speakers'):
        event.add('summary', u"{0} with {1}".format(content['title'],
                                                    content['speakers']))
    else:
        event.add('summary', u"{}".format(content['title']))

    event.add('dtstart', tz.localize(start_time))
    event.add('dtend', tz.localize(end_time))
    event.add('dtstamp', tz.localize(start_time))

    event.add('location', 'Room {}'.format(content['rooms']))

    event.add('uid', slug)

    tpl_url = 'https://2016.pycon.ca{0}'
    event.add('url', tpl_url.format(url_for('schedule.talk', slug=slug)))

    return event


@schedule.route('/<string:slug>.ics')
def talk_ics(slug):
    cal = Calendar()
    cal.add('prodid', '-//PyCon Canada 2016//2016.pycon.ca')
    cal.add('version', '2.0')

    if slug == 'schedule':
        schedule = get_data_file('schedule.json')

        # TODO: This should be refactored because it's really ugly.
        for day in schedule.get('days'):
            for slot in day.get('entries'):
                if slot.get('link'):
                    cal.add_component(event_ics(slot.get('link')))

                elif slot.get('talks'):
                    for room, talk in slot.get('talks').iteritems():
                        if talk:
                            cal.add_component(event_ics(talk))
                else:
                    start_time_str = '{0} {1}'.format(day['date'],
                                                      slot['start_time'])
                    start_time = datetime.strptime(start_time_str,
                                                   '%Y-%m-%d %H:%M:%S')

                    end_time_str = '{0} {1}'.format(day['date'],
                                                    slot['end_time'])
                    end_time = datetime.strptime(end_time_str,
                                                 '%Y-%m-%d %H:%M:%S')

                    event = Event()
                    event.add('summary', slot['title'])

                    event.add('dtstart', tz.localize(start_time))
                    event.add('dtend', tz.localize(end_time))
                    event.add('dtstamp', tz.localize(start_time))

                    cal.add_component(event)
    else:
        cal.add_component(event_ics(slug))

    headers = {
        'Content-Disposition': 'attachment;filename={0}.ics'.format(slug)
    }

    return Response(response=cal.to_ical(),
                    status=200,
                    mimetype='text/calendar',
                    headers=headers)

web/templates/pages/schedule/index.html
{% extends "layouts/page.html" %}

{% block title %}{{ _('Schedule') }} | {{ super() }}{% endblock %}

{% block page_class %}page--schedule{% endblock %}
{% block page_header_class %}page__header--schedule{% endblock %}
{% block page_content_class %}page__content--schedule{% endblock %}

{% block page_header %}
    <h1>{{ _('Schedule')|typogrify|safe }}</h1>
{% endblock %}

{% block page_content %}
    <div class="widget-schedule"></div>

    {% for day in schedule.days %}
    <h1 class="schedule__day schedule__day--{{ day.date.isoformat() }}">{{ day.date|format_date('full') }}</h1>

    <table class="schedule schedule--{{ day.date.isoformat() }}">
        <thead class="schedule__head">

            <tr>
                <th class="schedule__time">&nbsp;</th>
                {% for room in schedule.rooms %}
                <th class="schedule__room-name">{{ room.name|typogrify|safe }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody class="schedule__body">
            {% for entry in day.entries %}
            <tr class="schedule__row">
                <th class="schedule__time schedule__time--start-{{ day.date.isoformat() }}-{{ entry.start_time.strftime('%H-%M-%S') }} schedule__time--end-{{ day.date.isoformat() }}-{{ entry.end_time.strftime('%H-%M-%S') }}">
                    {{ entry.start_time|format_time('short')|typogrify|safe }}
                </th>

                {% if entry.talks %}
                {% for room in schedule.rooms %}
                {% set talk = get_talk(entry.talks[room.slug]) %}
                <td class="schedule__slot schedule__slot--room-{{ room.slug }} schedule__slot--time-{{ day.date.isoformat() }}-{{ entry.start_time.strftime('%H-%M-%S') }}" {% if talk.rowspan %}rowspan="{{ talk.rowspan[0] }}"{% endif %}>
                    <a href="{% if talk.link %}{{ talk.link }}{% else %}#{% endif %}" class="schedule__slot-link">
                        <span class="schedule__slot-title">
                            {% for t in talk.title %}{{ t|typogrify|safe }}{% endfor %}
                        </span>
                        <span class="schedule__slot-presenter">
                            {% for s in talk.speakers %}{{ s|typogrify|safe }}{% endfor %}
                        </span>
                    </a>
                </td>
                {% endfor %}
                {% else %}
                <td class="schedule__slot schedule__slot--time-{{ day.date.isoformat() }}-{{ entry.start_time.strftime('%H-%M-%S') }}" colspan="4">
                    {% if entry.link %}
                    <a href="{{ url_for('schedule.talk', slug=entry.link) }}" class="schedule__slot-link">
                    {% else %}
                    <span class="schedule__slot-link">
                    {% endif %}
                        <span class="schedule__slot-title">
                            {{ entry.title|typogrify|safe }}
                        </span>
                        {% if entry.content %}
                        <span class="schedule__slot-content">
                            {{ entry.content|typogrify|safe }}
                        </span>
                        {% endif %}
                    {% if entry.link %}
                    </a>
                    {% else %}
                    </span>
                    {% endif %}
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endfor %}

    <div class="page__section">
        <h1 class="schedule__day schedule__day--2016-11-14 schedule__day--2016-11-15">{{ _('14 &amp; 15 November, 2016') }}</h1>

        <h2>{{ _('PyCon Canada Sprints')|typogrify|safe }}</h2>

        <p style="text-align:center"><a href="https://github.com/pyconca/2016-wiki/wiki/Sprints" class="button button--red">{{ _('Find or Add a Project to the Wiki') }}</a></p>

        <p>{% trans %}PyCon Canada Development Sprints are two days of intensive learning and development on an open source project of your choice, in a team environment. It's a time to come together with colleagues, old and new, to share what you've learned and apply it to an open source project.{% endtrans %}</p>

        <p>{% trans %}PyCon provides the space and infrastructure (network, power, tables &amp; chairs); you bring your skills, humanity, and brainpower (oh! and don't forget your computer).{% endtrans %}</p>

        <h3>{{ _('Directions') }}</h3>

        <p>{% trans %}Code sprints will be held on the 6th floor of The Ryerson Digital Media Zone, located at 10 Dundas Street East (one block east of the PyCon venue, on the north east corner of Yonge and Dundas).{% endtrans %}</p>

        <p>{% trans %}From the ground floor, get to the 6th floor using the elevators to the right of the Starbucks, or from the fourth floor take the elevators inside the entrance to Spring Sushi (and across from the Ciniplex theater entrance).{% endtrans %}</p>

        <p>{% trans %}Sprints will be in room 631, and there will be obvious signage once you get off the elevators.{% endtrans %}</p>
    </div>

    {% block extra_code %}
        <link rel="stylesheet" href="{{ url_for('static', filename='widgets/schedule/app.css') }}"/>
        <script src="{{ url_for('static', filename='widgets/schedule/app.js') }}"></script>
    {% endblock %}
{% endblock %}

web/templates/pages/schedule/talk.html
{% extends "layouts/page.html" %}

{% block title %}{{ meta.title[0] }} {% if meta.speakers %}with {{ meta.speakers[0] }}{% endif %} | {{ super() }}{% endblock %}

{% block page_class %}page--talk{% endblock %}
{% block page_header_class %}page__header--talk{% endblock %}
{% block page_content_class %}page__content--talk{% endblock %}

{% block page_header %}
<h1>{{ meta.title[0]|typogrify|safe }} {% if meta.speakers %}<em>with {{ meta.speakers[0]|typogrify|safe }}</em>{% endif %}</h1>
<p class="lead">{{ meta.date[0]|format_date('EEE')|typogrify|safe }} {{ meta.start_time[0]|format_time('H:mm')|typogrify|safe }} | Rm. {{ meta.rooms[0] }}</p>
{% if meta.youtube %}<p class="lead"><a href="https://www.youtube.com/watch?v={{ meta.youtube[0] }}">{{ _('Watch on YouTube') }}</a></p>{% endif %}
{% endblock %}

{% block page_content %}
<div class="page__section talk">
    <div class="page__row">
        {% if meta.youtube %}
        <div class="page__col-12 talk__video">
            <div class="talk__video-wrapper">
                <iframe class="talk__video-embed" allowfullscreen src="https://www.youtube.com/embed/{{ meta.youtube[0] }}" frameborder="0"></iframe>
            </div>
        </div>
        {% endif %}

        <div class="{% if meta.photo %}page__col-8{% else %}page__col-12{% endif %} page__col--left">
            {% if meta.rooms[0] == 'Tutorial' %}
            <p style="text-align:center"><a href="https://github.com/pyconca/2016-wiki/wiki/Tutorials" class="button button--red">Sign Up for {% for speaker in meta.speakers %}{{ speaker }}'s{% endfor %} Tutorial</a></p>
            {% endif %}
            {{ content|safe }}
        </div>

        {% if meta.photo %}
        <div class="page__col-4 page__col--right">
            {% if meta.photo %}
            <img src="/static/images/speaker_photos/{{ meta.photo[0] }}" class="talk__image">
            {% endif %}

            {% if meta.twitter or meta.github %}
            <p>
                {% if meta.twitter %}
                <a href="https://twitter.com/{{ meta.twitter[0] }}" title="{% for speaker in meta.speakers %}{{ speaker }}{% endfor %} Twitter Profile">Twitter</a>
                {% endif %}
                {% if meta.github %}
                <a href="https://github.com/{{ meta.github[0] }}" title="{% for speaker in meta.speakers %}{{ speaker }}{% endfor %} GitHub Profile">GitHub</a>
                {% endif %}
            </p>
            {% endif %}
        </div>
        {% endif %}
    </div>
</div>

<div class="page__section">
    <p>
        <a href="{{ url_for('schedule.talk_ics', slug=slug) }}" title="iCalender File"><img data-file-extension="ics" data-src="{{ url_for('static', filename='images/icon-file.svg') }}" class="iconic iconic-md" alt="iCalendar File" /></a>

        <a href="{{ url_for('schedule.talk_json', slug=slug) }}" title="JSON File"><img data-file-extension="json" data-src="{{ url_for('static', filename='images/icon-file.svg') }}" class="iconic iconic-md" alt="JSON File" /></a>
    </p>
</div>
{% endblock %}

{% block schema_org %}
<script type="application/ld+json">
{
    "@context": "http://schema.org/",
    "@type": "Event",
    "name": "{{ meta.title[0] }} at {{ _('PyCon Canada 2016') }}",
    "description": "{{ _('Join your fellow Pythonistas for the fourth annual PyCon Canada, a weekend of talks, activities, fun and code!') }}",
    "image": "https://2016.pycon.ca{{ url_for('static', filename='images/pycon-2015-mc-paul-by-shiroyuki-facebook.jpg') }}",
    "url": "https://2016.pycon.ca{{ url_for(request.url_rule.endpoint, **request.view_args) }}",
    "startDate": "{{ meta.date[0] }}T{{ meta.start_time[0] }}",
    "endDate": "{{ meta.date[0] }}T{{ meta.end_time[0] }}",
    "location": {
        "@type": "Place",
        "name": "Ted Rogers School of Management",
        "address": {
            "@type": "PostalAddress",
            "streetAddress": "55 Dundas Street West",
            "postalCode": "M5G 2C3",
            "addressLocality": "Toronto",
            "addressRegion": "Ontario",
            "addressCountry": "Canada"
        }
    },
    {% if meta.speakers %}
    "performer": {
        "@type": "Person",
        "name": "{{ meta.speakers[0] }}"
    },
    {% endif %}
    "offers": {
        "@type": "Offer",
        "url": "https://www.eventbrite.com/e/pycon-canada-2016-tickets-27545680873"
    }
}
</script>
{% endblock %}

{% block twitter_card %}
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@pyconca">
<meta name="twitter:creator" content="@pyconca">
<meta name="twitter:title" content="{{ meta.title[0] }} {% if meta.speakers %}with {{ meta.speakers[0] }}{% endif %} at {{ _('PyCon Canada 2016') }}">
<meta name="twitter:description" content="{{ _('Join your fellow Pythonistas for the fourth annual PyCon Canada, a weekend of talks, activities, fun and code!') }}">
<meta name="twitter:image" content="https://2016.pycon.ca{{ url_for('static', filename='images/pycon-2015-mc-paul-by-shiroyuki-twitter-card.jpg') }}">
{% endblock %}

{% block opengraph %}
<meta property="og:title" content="{{ meta.title[0] }} {% if meta.speakers %}with {{ meta.speakers[0] }}{% endif %} at {{ _('PyCon Canada 2016') }}">
<meta property="og:description" content="{{ _('Join your fellow Pythonistas for the fourth annual PyCon Canada, a weekend of talks, activities, fun and code!') }}">
<meta property="og:type" content="website">
<meta property="og:url" content="https://2016.pycon.ca{{ url_for(request.url_rule.endpoint, **request.view_args) }}">
<meta property="og:image" content="https://2016.pycon.ca{{ url_for('static', filename='images/pycon-2015-mc-paul-by-shiroyuki-facebook.jpg') }}">
<meta property="og:image:type" content="image/jpeg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
{% endblock %}