web/views/api.py
from datetime import date

from flask import Blueprint, jsonify, url_for

api = Blueprint('api', __name__)


@api.route('/index.json')
def index():
    return jsonify({
        'name': 'PyCon Canada 2016',
        'conference': {
            'start_date': date(2016, 11, 12),
            'end_date': date(2016, 11, 13)
        },
        'sprints': {
            'start_date': date(2016, 11, 14),
            'end_date': date(2016, 11, 15)
        },
        'location': {
            'name': 'Ted Rogers School of Business',
            'address': {
                'street': '55 Dundas Street West',
                'city': 'Toronto',
                'province': 'Ontario',
                'country': 'Canada',
                'postal_code': 'M5G 2C3',
                'geo': {
                    'latitude': '43.65543',
                    'longitude': '-79.38310'
                }
            }
        },
        'routes': [
            url_for('schedule.talk_json', slug='schedule.json', lang='en'),
            url_for('schedule.talk_json', slug='schedule.json', lang='fr'),
            '/en/schedule/<talk-slug>.json',
            '/fr/schedule/<talk-slug>.json',
        ]
    })

web/views/pages.py
from flask import Blueprint, render_template, g

from web.utils import get_data_file, get_markdown_file

pages = Blueprint('pages', __name__)


@pages.route('/')
def index():
    """
    Landing page.
    """
    sponsors = get_data_file('sponsors.yml')

    return render_template('pages/index.html', sponsors=sponsors)


@pages.route('/code-of-conduct/')
def code_of_conduct():
    """
    Code of Conduct page.
    """
    content, meta = get_markdown_file('code-of-conduct', g.lang_code)

    return render_template('pages/code-of-conduct.html', content=content,
                           meta=meta)


@pages.route('/sponsors/')
def sponsors():
    """
    Sponsors page.
    """
    data = get_data_file('sponsors.yml')
    content, meta = get_markdown_file('sponsors', g.lang_code)

    return render_template('pages/sponsors.html', content=content, meta=meta,
                           sponsors=data)


@pages.route('/venue/')
def venue():
    """
    Venue page.
    """
    content = {
        'location': get_markdown_file('venue-location', g.lang_code)[0],
        'travel': get_markdown_file('venue-travel', g.lang_code)[0],
        'hotel': get_markdown_file('venue-hotel', g.lang_code)[0],
        'public_transit': get_markdown_file('venue-public-transit',
                                            g.lang_code)[0],
        'toronto': get_markdown_file('venue-toronto', g.lang_code)[0]
    }

    return render_template('pages/venue.html', content=content)


@pages.route('/about/')
def about():
    """
    About page.
    """
    content, meta = get_markdown_file('about', g.lang_code)
    team = get_data_file('team.json')
    sponsors = get_data_file('sponsors.yml')
    content, meta = get_markdown_file('about', g.lang_code)

    return render_template('pages/about.html', content=content, meta=meta,
                           team=team, sponsors=sponsors)


@pages.route('/volunteer/')
def volunteer():
    """
    Volunteer at PyCon Canada page.
    """
    content, meta = get_markdown_file('volunteer', g.lang_code)

    return render_template('pages/volunteer.html', content=content, meta=meta)


@pages.route('/guide/')
def guide():
    """
    Guide to things around the venue area page.
    """
    guide = get_data_file('guide.json')

    return render_template('pages/guide.html', guide=guide)

web/views/schedule.py
from datetime import datetime

import pytz
from icalendar import Calendar, Event

from flask import Blueprint, render_template, jsonify, Response, url_for, abort

from web.utils import get_data_file, get_markdown_file

schedule = Blueprint('schedule', __name__)

tz = pytz.timezone('Canada/Eastern')


@schedule.route('/')
def index():
    """
    Schedule index page.
    """
    schedule = get_data_file('schedule.json')

    return render_template('pages/schedule/index.html', schedule=schedule)


@schedule.route('/<string:slug>/')
def talk(slug):
    """
    Talk details page.
    """
    content, meta = get_markdown_file('talks/{}'.format(slug), 'en')

    return render_template('pages/schedule/talk.html', content=content,
                           meta=meta, slug=slug)


@schedule.route('/<string:slug>.json')
def talk_json(slug):

    if slug == 'schedule':
        content = get_data_file('schedule.json')
    else:
        description, content = get_markdown_file('talks/{}'.format(slug), 'en')

        # The Markdown Meta extension gives us everything in lists.
        # So this is a simple converter.
        for k, v in content.items():
            content[k] = v[0]

        content['description'] = description

    return jsonify(content)


def event_ics(slug):
    description, content = get_markdown_file('talks/{}'.format(slug), 'en')

    if not content:
        abort(404)

    for k, v in content.items():
        content[k] = v[0]

    start_time = datetime.strptime('{0} {1}'.format(content['date'],
                                                    content['start_time']),
                                   '%Y-%m-%d %H:%M:%S')

    end_time = datetime.strptime('{0} {1}'.format(content['date'],
                                                  content['end_time']),
                                 '%Y-%m-%d %H:%M:%S')

    event = Event()

    if content.get('speakers'):
        event.add('summary', u"{0} with {1}".format(content['title'],
                                                    content['speakers']))
    else:
        event.add('summary', u"{}".format(content['title']))

    event.add('dtstart', tz.localize(start_time))
    event.add('dtend', tz.localize(end_time))
    event.add('dtstamp', tz.localize(start_time))

    event.add('location', 'Room {}'.format(content['rooms']))

    event.add('uid', slug)

    tpl_url = 'https://2016.pycon.ca{0}'
    event.add('url', tpl_url.format(url_for('schedule.talk', slug=slug)))

    return event


@schedule.route('/<string:slug>.ics')
def talk_ics(slug):
    cal = Calendar()
    cal.add('prodid', '-//PyCon Canada 2016//2016.pycon.ca')
    cal.add('version', '2.0')

    if slug == 'schedule':
        schedule = get_data_file('schedule.json')

        # TODO: This should be refactored because it's really ugly.
        for day in schedule.get('days'):
            for slot in day.get('entries'):
                if slot.get('link'):
                    cal.add_component(event_ics(slot.get('link')))

                elif slot.get('talks'):
                    for room, talk in slot.get('talks').iteritems():
                        if talk:
                            cal.add_component(event_ics(talk))
                else:
                    start_time_str = '{0} {1}'.format(day['date'],
                                                      slot['start_time'])
                    start_time = datetime.strptime(start_time_str,
                                                   '%Y-%m-%d %H:%M:%S')

                    end_time_str = '{0} {1}'.format(day['date'],
                                                    slot['end_time'])
                    end_time = datetime.strptime(end_time_str,
                                                 '%Y-%m-%d %H:%M:%S')

                    event = Event()
                    event.add('summary', slot['title'])

                    event.add('dtstart', tz.localize(start_time))
                    event.add('dtend', tz.localize(end_time))
                    event.add('dtstamp', tz.localize(start_time))

                    cal.add_component(event)
    else:
        cal.add_component(event_ics(slug))

    headers = {
        'Content-Disposition': 'attachment;filename={0}.ics'.format(slug)
    }

    return Response(response=cal.to_ical(),
                    status=200,
                    mimetype='text/calendar',
                    headers=headers)

web/templates/pages/about.html
{% extends "layouts/page.html" %}

{% block title %}{{ _('About') }} | {{ super() }}{% endblock %}

{% block page_class %}page--about{% endblock %}
{% block page_header_class %}page__header--about{% endblock %}
{% block page_content_class %}page__content--about{% endblock %}

{% block page_header %}
    <h2>{{ _("PyCon Canada is an initiative to strengthen the Canadian Python community.")|typogrify|safe }}</h2>
{% endblock %}

{% block page_content %}
    <div class="page__section">
        {{ content|safe }}
    </div>
    
    <div class="page__section">
        <div class="page__row">
            <div class="page__col page__col--left">
                <h2>{{ _("Join the Conversation") }}</h2>
            
                <p>{{ _('Be sure to use <a href="https://twitter.com/intent/tweet?button_hashtag=PyConCA2016">#PyConCA2016</a>. We love hearing from our community members!') }}</p>
            
                <h2>{{ _('Key Contacts') }}</h2>
            
                <ul>
                    <li>{{ _('The organizing committee can be contacted at <a href="mailto:organizers@pycon.ca">organizers@pycon.ca</a>.') }}</li>
                    <li>{{ _('The board can be contacted privately at <a href="mailto:board@pycon.ca">board@pycon.ca</a>.') }}</li>
                    <li>{{ _('You can also find us on: <a href="https://github.com/pyconca/">github.com/pyconca/</a>.') }}</li>
                </ul>
            </div>
        
            <div class="about-page__twitter-timeline page__col page__col--right">
                <a class="twitter-timeline" data-dnt="true" href="https://twitter.com/hashtag/PyConCA2016" data-widget-id="765372112991358978">{{ _('#PyConCA2016 Tweets') }}</a>
            </div>
        </div>
    </div>
    
    <div class="page__section">
        <h2>{{ _('Organisers') }}</h2>

        <p>
            {% for person in team['organisers'] %}
            <a href="{{ person.link }}">{{ person.name|typogrify|safe }}</a> {% if not loop.last %}<span class="separator">&bull;</span>{% endif %}
            {% endfor %}
        </p>
    </div>
    
    {#
    <div class="page__section">
        <div class="page__row">
            <div class="page__col page__col--left">
                <h2>{{ _('Organisers') }}</h2>
            
                <p>
                    {% for person in team['organisers'] %}
                    <a href="{{ person.link }}">{{ person.name|typogrify|safe }}</a> {% if not loop.last %}<span class="separator">&bull;</span>{% endif %}
                    {% endfor %}
                </p>
            </div>
        
            <div class="page__col page__col--right">
                <h2>{{ _('Volunteers') }}</h2>
            
                <p>
                    {% for person in team['volunteers'] %}
                    <a href="{{ person.link }}">{{ person.name|typogrify|safe }}</a> {% if not loop.last %}<span class="separator">&bull;</span>{% endif %}
                    {% endfor %}
                </p>
            </div>
        </div>
    </div>
    #}
    
    {% if sponsors %}
    <div class="page__section about-page__sponsors">
        <h2>{{ _('Sponsors') }}</h2>
        
        {% for level in sponsors %}
        {% for sponsor in level.entries %}
        <a href="{{ sponsor[g.lang_code].url }}" title="{{ sponsor[g.lang_code].name }}" class="about-page__sponsor-link">
            <img src="{{ url_for('static', filename=sponsor.logo) }}" class="about-page__sponsor-logo" alt="{{ sponsor[g.lang_code].name }}">
        </a>
        {% endfor %}
        {% endfor %}
    </div>
    {% endif %}
{% endblock %}

web/templates/pages/api.html
{% extends "layouts/page.html" %}

{% block title %}{{ _('API') }} | {{ super() }}{% endblock %}

{% block page_class %}page--api{% endblock %}
{% block page_header_class %}page__header--api{% endblock %}
{% block page_content_class %}page__content--api{% endblock %}

{% block page_header %}
<h1>{{ _('API') }}</h1>
{% endblock %}

{% block page_content %}
<div class="page__section">
    {{ content|safe }}
</div>
{% endblock %}

web/templates/pages/code-of-conduct.html
{% extends "layouts/page.html" %}

{% block title %}{{ _('Code of Conduct') }} | {{ super() }}{% endblock %}

{% block page_class %}page--code-of-conduct{% endblock %}
{% block page_header_class %}page__header--code-of-conduct{% endblock %}
{% block page_content_class %}page__content--code-of-conduct{% endblock %}


{% block page_header %}
<h1>{{ _('PyCon Canada is committed to providing a safe and welcoming atmosphere for all attendees.')|typogrify|safe }}</h1>
{% endblock %}

{% block page_content %}
<div class="page__section">
    {{ content|safe }}
</div>
{% endblock %}

web/templates/pages/guide.html
{% extends "layouts/page.html" %}

{% block title %}{{ _('Guide') }} | {{ super() }}{% endblock %}

{% block page_class %}page--guide{% endblock %}
{% block page_header_class %}page__header--guide{% endblock %}
{% block page_content_class %}page__content--guide{% endblock %}

{% block page_header %}
<h1>{{ _('Welcome to Toronto')|typogrify|safe }}</h1>
<p>{% trans %}Here are some of our favorite spots around <strong>Ryerson University</strong>.{% endtrans %}</p>
{% endblock %}

{% block page_content %}
    {% for section in guide %}
    <div class="page__section guide-page__section guide-page__section--{{ section.slug }}">
        <h2>{{ section.name }}</h2>
        
        <div class="guide-page__place-list">
            {% for place in section.places %}
            <div class="guide-page__place">
                <h3 class="guide-page__place-name">{{ place.name|safe }}</h3>
                
                <p class="guide-page__place-address">{{ place.address }}</p>
                
                <p class="guide-page__place-notes">{{ place.notes }}</p>
                
                {% if place.tags %}
                <p class="guide-page__place-tag-list">
                    {% for tag in place.tags %}
                    <span class="guide-page__place-tag">{{ tag }}</span>
                    {% endfor %}
                </p>
                {% endif %}
                
                {% if place.links %}
                <p class="guide-page__place-link-list">
                    {% for slug, link in place.links.items() %}
                    <a href="{{ link }}" class="guide-page__place-link guide-page__place-link--{{ slug }}">{{ slug }}</a>
                    {% endfor %}
                </p>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
{% endblock %}

web/templates/pages/index.html
{% extends "layouts/base.html" %}

{% block body_class %}body--homepage{% endblock %}

{% block body %}
<div class="homepage">
    <div class="homepage__wrapper">
        <div class="homepage__header">
            <a href="#" class="navigation__menu header__navigation-menu homepage__navigation__menu" id="js-navigation-button">MENU</a>
            <div class="table">
                <ul class="navigation homepage__navigation" id="js-navigation-menu">
                    <li class="navigation__item"><a class="navigation__link" href="{{ url_for('pages.index') }}">{{ _('Home') }}</a></li>
                    <li class="navigation__item"><a class="navigation__link" href="{{ url_for('pages.about') }}">{{ _('About') }}</a></li>
                    <li class="navigation__item"><a class="navigation__link" href="{{ url_for('pages.venue') }}">{{ _('Venue') }}</a></li>
                    <li class="navigation__item"><a class="navigation__link" href="{{ url_for('pages.volunteer') }}">{{ _('Volunteer') }}</a></li>
                    <li class="navigation__item"><a class="navigation__link" href="{{ url_for('pages.sponsors') }}">{{ _('Sponsors') }}</a></li>
                    <li class="navigation__item"><a class="navigation__link" href="{{ url_for('schedule.index') }}">{{ _('Schedule') }}</a></li>
                </ul>
            </div>
        </div>

        <div class="homepage__content">
            <img src="{{ url_for('static', filename='images/logo.svg') }}" alt="PyCon Canada" class="homepage__logo">

            <h2 class="homepage__heading">{{ _('12-15 November 2016') }}, {{ _('Toronto') }}</h2>

            <p class="homepage__copy">{{ _('12-13 November Conference<br/>14-15 November Sprints') }}</p>

            <!--
            <p class="homepage__copy">{{ _('Join your fellow Pythonistas for the fourth annual PyCon Canada, a weekend of talks, activities, fun and code!') }}</p>
            -->

            <p class="homepage__button">
                <a href="{{ url_for('schedule.index') }}" class="button button--primary">{{ _('View the schedule') }}</a>

                <a href="http://eepurl.com/bs9mG9" class="button button--secondary">{{ _('Join our mailing list') }}</a>
            </p>
        </div>

        {% if sponsors %}
        <div class="homepage__sponsors">
            {% for level in sponsors %}
            {% for sponsor in level.entries %}
            <a href="{{ sponsor[g.lang_code].url }}" title="{{ sponsor[g.lang_code].name }}" class="homepage__sponsor-link">
                <img src="{% if sponsor.logo_dark %}{{ url_for('static', filename=sponsor.logo_dark) }}{% else %}{{ url_for('static', filename=sponsor.logo) }}{% endif %}" class="homepage__sponsor-logo" alt="{{ sponsor[g.lang_code].name }}">
            </a>
            {% endfor %}
            {% endfor %}
        </div>
        {% endif %}

        <div class="homepage__footer">
            <p>
                {% if g.lang_code=='fr' %}
                <a href="{{ url_for(request.url_rule.endpoint, lang_code='en') }}" hreflang="en">English</a>
                {% else %}
                <a href="{{ url_for(request.url_rule.endpoint, lang_code='fr') }}" hreflang="fr">Fran&ccedil;ais</a>
                {% endif %}
                &bull;
                <a href="{{ url_for('pages.code_of_conduct') }}">{{ _('Code of Conduct') }}</a>
            </p>
        </div>
    </div>
</div>
{% endblock %}

web/templates/pages/sponsors.html
{% extends "layouts/page.html" %}

{% block title %}{{ _('Sponsors') }} | {{ super() }}{% endblock %}

{% block page_class %}page--sponsors{% endblock %}
{% block page_header_class %}page__header--sponsors{% endblock %}
{% block page_content_class %}page__content--sponsors{% endblock %}

{% block page_header %}
    <h1 class="page__title">{{ _('Our Sponsors') }}</h1>
    <p class="page__subtitle">{{ _('We thank our fantastic sponsors who help make this event possible. <a href="mailto:sponsorship@pycon.ca">Get in touch</a> if your organization would like to support PyCon Canada 2016.') }}</p>
{% endblock %}

{% block page_content %}
    <div class="page__section">
        {{ content|safe }}
    </div>

    {% for level in sponsors %}
    <div class="page__section sponsor-level sponsor-level--{{ level.level['en'].lower() }}">
        <div class="sponsor-level__header">
            <h1 class="sponsor-level__title">
                {% if g.lang_code=='fr' %}
                {{ level.level['fr'] }}
                {% else %}
                {{ level.level['en'] }}
                {% endif %}
            </h1>
        </div>

        {% for sponsor_data in level.entries %}
            {% if g.lang_code=='fr' %}{% set sponsor = sponsor_data.fr %}{% else %}{% set sponsor = sponsor_data.en %}{% endif %}
            <div class="sponsor">
                <div class="page__row">
                    <div class="page__col">
                        <a href="{{ sponsor.url }}" class="sponsor__link" title="{{ sponsor.name }}">
                            <img src="{{ url_for('static', filename=sponsor_data.logo) }}" class="sponsor__logo" alt="{{ sponsor.name }}">
                        </a>

                        {% if sponsor.twitter %}
                        <ul>
                            <li><a href="https://twitter.com/{{ sponsor.twitter }}" class="sponsor__twitter twitter-follow-button" data-show-count="false">{{ _('Follow @') }}{{ sponsor.twitter }}</a></li>
                        </ul>
                        {% endif %}
                    </div>

                    <div class="page__col">
                        <div class="sponsor__description">
                            {{ sponsor.description|markdown }}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% endfor %}
{% endblock %}

web/templates/pages/venue.html
{% extends "layouts/page.html" %}

{% block title %}{{ _('Venue') }} | {{ super() }}{% endblock %}

{% block page_class %}page--venue{% endblock %}
{% block page_header_class %}page__header--venue{% endblock %}
{% block page_content_class %}page__content--venue{% endblock %}

{% block page_header %}
<h1>{{ _('Venue') }}</h1>
{% endblock %}

{% block page_content %}
<div class="page__section">
    <div class="page__row">
        <div class="page__col">
            {{ content.location|safe }}
        </div>
    
        <div class="page__col">
            <div class="venue-page__map" id="js-venue-map"></div>
        </div>
    </div>
</div>

<div class="page__section">
    {{ content.travel|safe }}
</div>

<div class="page__section">
    {{ content.hotel|safe }}
</div>

<div class="page__section">
    {{ content.public_transit|safe }}
</div>

<div class="page__section">
    {{ content.toronto|safe }}
</div>
{% endblock %}

web/templates/pages/volunteer.html
{% extends "layouts/page.html" %}

{% block title %}{{ _('Volunteer') }} | {{ super() }}{% endblock %}

{% block page_class %}page--volunteer{% endblock %}
{% block page_header_class %}page__header--volunteer{% endblock %}
{% block page_content_class %}page__content--volunteer{% endblock %}

{% block page_header %}
<h1>{{ _('Volunteer') }}</h1>
{% endblock %}

{% block page_content %}
<div class="page__section">
    {{ content|safe }}
</div>
{% endblock %}